# Mysql\u6570\u636E\u5E93
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-boot-demo?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT&nullCatalogMeansCurrent=true
    username: root
    password: 123456
# 4.8.3 自动重启 -> 记录条件评估中的变化
# 对自动配置的影响评估
#  devtools:
#    restart:
#      log-condition-evaluation-delta: false

# 4.8.2 属性默认值
#  测试 WEB请求打印详细日志
#  mvc:
#    log-request-details: false
#  devtools:
#    add-properties: false
#  codec:
#    log-request-details: true
#logging:
#  level:
#    web: debug
