spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./spring-boot-demo
    username: root
    password: 123456

context:
  initializer:
    classes: com.springboot.demo.initializer.MyInitializer3
