spring:
#  profiles:
#    active:
#      - test
  main:
    banner-mode: log
  output:
    ansi:
      enabled: always
#  banner:
#    location: classpath:static/banner.txt
  #已经不支持图片banner
#  banner:
#    image:
#      location: classpath:banner.png
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./spring-boot-demo
    username: root
    password: 123456
  # 开启h2页面控制台
  h2:
    console:
      enabled: true
  # sql初始化
  sql:
    init:
      platform: h2

#context:
#  initializer:
#    classes: com.springboot.demo.initializer.MyInitializer3

#context:
#  listener:
#    classes: com.springboot.demo.listeners.MyApplicationListener

logging:
  file:
    path: log
#  level:
#    org.springframework: debug

me: 4444

