spring:
  main:
    banner-mode: log
  #已经不支持图片banner
#  banner:
#    image:
#      location: classpath:banner.png
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./spring-boot-demo
    username: root
    password: 123456

#context:
#  initializer:
#    classes: com.springboot.demo.initializer.MyInitializer3

#context:
#  listener:
#    classes: com.springboot.demo.listeners.MyApplicationListener

logging:
  file:
    path: log